### ISSUE TITLE
Use of undefined constant DS

### ISSUE THREAD

**Issue by moddyn6** [OblikStudio/kirby-link-field#1]
Hey first up neat plugin, great work!

When installing it in my current kirby-setup I'm instantly hit with a 500 errorcode though.
It seems like the DS constant was removed from kirby core some time ago and was not added back in (https://github.com/getkirby/kirby/issues/225 seems inconclusive).

So now the fist require fails with 
`PHP Fatal error:  require_once(): Failed opening required '/var/www/kirby/site/plugins/link-fieldDSsrcDSLink.php' `

Replacing DS with PHP's `DIRECTORY_SEPARATOR` (https://www.php.net/manual/en/dir.constants.php) should fix this

**Comment by hdodov** [comment]
During the plugin's development, I've used the latest Kirby version and didn't have this problem. In the issue you mentioned, Bastian said:

>The separator thing doesn’t seem to be an issue on Windows anymore. But it would make sense to define it anyway for compatibility reasons.

So they've added the constant and it should exist? Could you check your Kirby version? I'll look into it soon. 👍

**Comment by moddyn6** [comment]
You are right, my apologies.
When trying it with the newest plain-/starterkit it works flawlessly.

Seems like my setup tries to load the plugin code during the autoloader instead of the render process and for that never reaches the bottom of the bootstrap.php where DS is defined.

I will have to investigate the reason for that. 
Thanks for your quick reply 👍

**Comment by philipmarnef** [comment]
I'm having the same issue. I'm on 3.1.4 but the site was built on dev kit originally, half a year ago.

**Comment by hdodov** [comment]
I'm going to launch an update soon where I change `DS` to `DIRECTORY_SEPARATOR`. I think using the native PHP value is better either way. I don't understand why this happens, though. It shouldn't.

**Comment by hdodov** [comment]
[Here it is.](https://github.com/OblikStudio/kirby-link-field/releases/tag/1.0.2)

**Comment by philipmarnef** [comment]
Top, problem solved.
