### ISSUE TITLE
Mail link field in structure

### ISSUE THREAD

**Issue by christophknoth** [OblikStudio/kirby-link-field#31]
If I add a link field in a structure and I use 
```
options:
  - email
```
it will show a normal website link placeholder text like: "example.com". 

As a workaround I used in the structure field:
```
options:
  - email
  - page
```
and then I can select the email link and get the "mail@example.com" placeholder.

**Comment by foxacid** [comment]
Same issue here.

**Comment by hdodov** [comment]
This seems to be fixed in the latest version. Note that you'll have to change `options` to `linkTypes`, as we've discussed in [#18](https://github.com/OblikStudio/kirby-link-field/issues/18#issuecomment-1165800376).
