### ISSUE TITLE
Check for `required: true`

### ISSUE THREAD

**Issue by bvdputte** [OblikStudio/kirby-link-field#45]
Please check for default Kirby options such as `required: true`. 

In my tests I was able to save a page where this field was empty, nonetheless in the blueprint it was set as required.

**Comment by jonasfeige** [comment]
> Please check for default Kirby options such as `required: true`.
> 
> In my tests I was able to save a page where this field was empty, nonetheless in the blueprint it was set as required.

+1 for this feature, would be really critical.

**Comment by hdodov** [comment]
Sorry for the huge response time, I've got too many things... Last time I tried to implement the `required` option, I had issues with Kirby, as far as I can remember. I'll try to look into it soon! 👍

**Comment by hdodov** [comment]
This should be fixed in [4.0.0-rc.2](https://github.com/OblikStudio/kirby-link-field/releases/tag/4.0.0-rc.2).
