### ISSUE TITLE
Global options don't work

### ISSUE THREAD

**Issue by bvdputte** [OblikStudio/kirby-link-field#51]
I've tried setting global options for the link field, but it doesn't seem to work?

Here's what I've tried in my config:

```php
'oblik.linkField' => [
    'settings' => [
        'popup' => false,
        'hash' => false
    ]
],
```
and
```php
'oblik.linkField.settings.popup' => false,
'oblik.linkField.settings.hash' => false,
```
I think I followed what is in the readme: https://github.com/OblikStudio/kirby-link-field#blueprint

Thx!

**Comment by hdodov** [comment]
It should be fine in the new [4.0.0-rc.1 release](https://github.com/OblikStudio/kirby-link-field/releases/tag/4.0.0-rc.1).
