### ISSUE TITLE
support for kirby 3.7+

### ISSUE THREAD

**Issue by jaro-io** [OblikStudio/kirby-link-field#54]
hey there💡 ✨
looks like there are some very minor but breaking changes for kirby 3.7.+ as a function you are using has been deprecated. would be super cool if you would find a minute and update this.

🙏🏻 

<img width="992" alt="Screenshot 2022-06-17 at 13 33 33" src="https://user-images.githubusercontent.com/20298313/174291237-c103ea4c-9494-4ae9-8bb5-9bff947a9c43.png">

**Comment by hdodov** [comment]
I'm working on it! I think I'll have it in a couple of days, because there's some other maintenance stuff I want to clear out.

**Comment by hdodov** [comment]
@jaro-io I tested with the latest Kirby [3.7.0-rc.2](https://github.com/getkirby/kirby/releases/tag/3.7.0-rc.2) and I don't see this error. There are minor design issues, but the plugin itself works.

The error message you've sent says:

> `Cms\Page::panelPickerData()` has been deprecated and will be removed in Kirby 3.8.0. Use `$page->panel()->pickerData()` instead.

I can't find anything like that in the Kirby source code either. Can you share your exact Kirby version?

**Comment by hdodov** [comment]
Never mind, I somehow reproduced it. The weird thing is that everything worked the first time I selected a page and only saw an error on the second try. I'll look into it.

**Comment by hdodov** [comment]
I've fixed this particular issue you've described, but there are others I discovered. I'll fix them all and once 3.7 is officially released and everything is still working fine, I'll release a new version of the plugin.

**Comment by jaro-io** [comment]
@hdodov fyi, i was using `3.7.0-rc.1` when encountering the error above. haven’t checked with `rc.2` yet. in the newest release notes i also saw that many falsely triggered deprecation warnings had been fixed. maybe this is also related to your plugin. just wanted to mention it, hope it helps.

anyway, thank you so much for working on such a quick fix for this.
❤️ ✨

**Comment by hdodov** [comment]
I've created the [4.0.0-rc.1](https://packagist.org/packages/oblik/kirby-link-field#4.0.0-rc.1) release with the Kirby 3.7 fixes. You can check it and let me know if something's wrong.

**Comment by jaro-io** [comment]
seems to be fixed, perfect! thank you so much! 🌻

**Comment by jaro-io** [comment]
@hdodov hmm, having another issue.. seems like this might also be related to `3.7`.. my pages query gets ignored completely. showing the whole index instead of the page’s children. query works fine though when switching to a `pages` field instead of a `link` field.

```yml
type: link
pages:
    query: page.children
linkTypes:
    - page
    - url
    - email
    - tel
```

**Comment by tobimori** [comment]
Found another issue:

When the link field is in a structure and used to select a page, no page name is shown:
<img width="901" alt="CleanShot 2022-06-27 at 11 02 25@2x" src="https://user-images.githubusercontent.com/29142128/175902056-05f9209d-9c24-4851-9c69-7aaaf767f604.png">

<img width="899" alt="CleanShot 2022-06-27 at 11 02 44@2x" src="https://user-images.githubusercontent.com/29142128/175902080-2f78c0b2-2919-476f-9ab5-69d4202bb4df.png">

But it's apparently saved correctly anyways:
<img width="283" alt="CleanShot 2022-06-27 at 11 02 56@2x" src="https://user-images.githubusercontent.com/29142128/175902120-ed07d5c1-52ea-4038-aa6d-47e0c15cf186.png">

**Comment by hdodov** [comment]
@jaro-io that was a regression. It should be fixed in [4.0.0-rc.2](https://github.com/OblikStudio/kirby-link-field/releases/tag/4.0.0-rc.2).

@tobimori can you reproduce this issue in the new [4.0.0-rc.2](https://github.com/OblikStudio/kirby-link-field/releases/tag/4.0.0-rc.2) release as well?

**Comment by tobimori** [comment]
yes, issue continues to exist @hdodov

**Comment by tobimori** [comment]
works!

**Comment by jaro-io** [comment]
@hdodov thank you so much! working with [4.0.0-rc.2](https://github.com/OblikStudio/kirby-link-field/releases/tag/4.0.0-rc.2) on my side
