### ISSUE TITLE
Cms\Page::panelPickerData() has been deprecated Error in Kirby 3.7.2

### ISSUE THREAD

**Issue by seehat** [OblikStudio/kirby-link-field#58]
2 occurrences of `$page->panelPickerData($settings);` in `index.php` on line 110 and 120 need to be replaced with `$page->panel()->pickerData($settings);`

**Comment by hdodov** [comment]
Are you sure you've updated the plugin to the latest version (4.0.1)? I've fixed exactly this issue in https://github.com/OblikStudio/kirby-link-field/commit/9de415b6156abfd68d6e037a79b0dbda2688d856.

In Kirby 3.7.3-rc.1, I see no errors.

**Comment by seehat** [comment]
Oh I am so sorry for bringing up this issue. I didn't get the newest major version. You are right.
