### ISSUE TITLE
Link type not resetted after deleting a link (4.0.1)

### ISSUE THREAD

**Issue by doldenroller** [OblikStudio/kirby-link-field#61]
Hi,
first of all thanks for the great plugin.

But I noticed that if you delete a link, the the type remains in the content file like this:

````
Link: type: page
````

In result you can't check if the link field is empty or not. In some cases this can break the page, e.g. if you use the ````$page->link()->toLinkObject()->tag()````method.

I fixed it for myself by adding this to the if-clause where ````$data['value']````in the index.php end of line 85:

````
elseif(empty($data['value'])){
    $data['type'] = false;
}
````

This resets the type if the value is empty. Maybe this helps anybody with the same problem.

Cheers
tom

**Comment by AEWebdesign** [comment]
i have the same issue, thanks for the workaround

**Comment by hdodov** [comment]
With the new version of the plugin, you should be able to use `isEmpty()` to check if the link is empty. Check the [release notes](https://github.com/OblikStudio/kirby-link-field/releases/tag/5.0.0).
