### ISSUE TITLE
config option to hide image preview

### ISSUE THREAD

**Issue by bogdancondorachi** [OblikStudio/kirby-link-field#64]
Hi there, I'm suggesting a config option to show no image or icon preview at all on page option

I've tried to add it like this but it seems to not work as it works on the pages field

`'pages' => function ($value = []) {
					return array_merge([
						'image' => false,
						'query' => 'site.pages',
						'search' => true,
					], $value);
				},`

**Comment by hdodov** [comment]
I think you can accomplish what you want by specifying it in the blueprint. Check [the docs](https://github.com/OblikStudio/kirby-link-field#pagesfiles-settings). Maybe something like this?

```yml
fields:
  myfield:
    type: link
    pages:
      image: false
```
