### ISSUE TITLE
Link field saves page slug/id instead of uuid in Kirby 3.8

### ISSUE THREAD

**Issue by AEWebdesign** [OblikStudio/kirby-link-field#65]
The link field should save the new page uuid which was introduced in kirby 3.8 instead of the page slug/id.

![image](https://user-images.githubusercontent.com/55782923/193599950-7dabb698-30b2-4997-8e47-2cd68f3922b3.png)

**Comment by afbora** [comment]
@AEWebdesign Does the plugin not work in 3.8 now? Or do you want to see the `uuid` feature in this plugin?

**Comment by AEWebdesign** [comment]
@afbora the plugin works, but i think with kirby 3.8 no page slugs/ids should be saved anymore or, right?

**Comment by afbora** [comment]
Yes. UUID is of course much more stable, but this case not a incompatibility, a decision for the developer.

**Comment by AEWebdesign** [comment]
@afbora ok thanks, i will make a pull request

**Comment by iskrisis** [comment]
Actually i think it doesn't work with previews inside the page select component.

https://share.cleanshot.com/Vk5lpQFu8v0EYEuKg1yk

It doesnt matter if the site has `content.uuid` set to `false`. Even when the fields save in the ID/slug format it doesn't preview correctly.

**Comment by hdodov** [comment]
Yep, it makes sense to store the UUID, otherwise slug changes will break links. I'll update it.

**Comment by hdodov** [comment]
This is available in the new version of the plugin. Check the [release notes](https://github.com/OblikStudio/kirby-link-field/releases/tag/5.0.0).

**Comment by jaro-io** [comment]
@hdodov quick questuin, will v5 also work if uuids are [disabled through the config](https://github.com/getkirby/kirby/pull/4755)?

**Comment by hdodov** [comment]
@jaro-io I don't think so. Link Field currently has no logic to handle missing UUIDs and relies on them. However, maybe calling `$page->uuid()` when UUIDs are disabled falls back to returning the slug and everything would work alright? It depends on how it's implemented in Kirby and I can't test it right now. It'd be great if you could check it out and open a new issue, in case we have a problem. 🙏

**Comment by jaro-io** [comment]
@hdodov just tested myself and can confirm that in this case, the slug is saved as a fallback. so from what i see, no problems with your plugin. perfect! 🥳✨
