### ISSUE TITLE
Mail and Popup not working

### ISSUE THREAD

**Issue by manuel-fleig** [OblikStudio/kirby-link-field#66]
I used the plugin for internal links and it worked perfectly, but i cannot get Mail and Popup for external links running. What could be wrong? (using Kirby 3.7.5)

**Comment by hdodov** [comment]
Could you post some code? What do you have in the blueprint, the template, and the TXT file?

**Comment by manuel-fleig** [comment]
was just a stupid typo, so no problems now :)
