### ISSUE TITLE
Link Field in structure not working

### ISSUE THREAD

**Issue by AEWebdesign** [OblikStudio/kirby-link-field#67]
If we have the link field inside of a structure field, the page title isn't visible:

![image](https://user-images.githubusercontent.com/55782923/198018883-6064d5a2-c978-4540-999f-5918eebff6c6.png)

Tested Versions:
Kirby Version: 3.7.4
Plugin Version: 4.0.1

Kirby Version: 3.8.1.1
Plugin Version: 4.0.1

Can someone confirm that behaviour?

**Comment by hdodov** [comment]
That's probably due to the Kirby 3.8 update. I'll look into it.

**Comment by hdodov** [comment]
I can't reproduce this with your specified versions of Kirby, as well as with the newest one (3.8.2). I've published a [new version of the plugin](https://github.com/OblikStudio/kirby-link-field/releases/tag/5.0.0). Does that still appear there as well?

**Comment by SamuelRiversMoore** [comment]
I had the same issue and finally found out I was using the key `options` instead of `linkTypes` to set up the available types of links. Probably because of copy-pasting the field from another website with an older version of the plugin installed.
