### ISSUE TITLE
Expand arguments to add HTML

### ISSUE THREAD

**Issue by macx** [OblikStudio/kirby-link-field#7]
I would like to use `$link->tag()`, but I need a HTML option to add a custom Icon-Tag after the title. This would be nice to have.

Two more problems:

* Unfortunately I only get the url using `$lik->attr()` instead of the whole arguments chain including `target="_blank"`
* How can I get the `type` if the related url is a internal page or url?

**Comment by hdodov** [comment]
The `tag()` method is meant for simple text-based links. You can still pass `class`, `id`, or any other attribute for the `<a>` tag. But for custom HTML, you're better off writing the markup yourself and using the other Link methods for the relevant link attributes.

`attr()` should return the `target` attribute if the `popup` setting is `true`. Is it?

You can get the type by using `$link->type`. You can also use `$link->value`, `$link->popup` etc.
