### ISSUE TITLE
toValidLink() method not working with "email" and "tel" types

### ISSUE THREAD

**Issue by SamuelRiversMoore** [OblikStudio/kirby-link-field#74]
When picking the "email" or "tel" types, using the `$field->toValidLink()` method returns nothing while `$field->toLinkObject()` returns a valid link.

After a short investigation I would say this is related to the way the [`$link->isEmpty()`](https://github.com/OblikStudio/kirby-link-field/blob/858a862ac901b4d82c5de2c29ab2851c8c93fd1f/src/Link.php#L128) method works. This method only checks if the $link->url() is not null, which means it only works with the "url", "page" and "file" types. Replacing this `$link->url()` by a call to `$link->href()` would includes the "email" and "tel" types verification.

**Comment by hdodov** [comment]
This is exactly what I've changed in the latest release a few days ago. Check out [5.2.1](https://github.com/OblikStudio/kirby-link-field/releases/tag/5.2.1).

**Comment by SamuelRiversMoore** [comment]
Ah yes! Thank you, happy to be late ;)
