### ISSUE TITLE
__toString() can return null and produces type error in PHP 8+

### ISSUE THREAD

**Issue by pstaender** [OblikStudio/kirby-link-field#75]
Hi @hdodov,

`TypeError Oblik\LinkField\Link::__toString(): Return value must be of type string, null returned` if `href()` returns null. It could be fixed in https://github.com/OblikStudio/kirby-link-field/blob/d12257715d804705bc9c0b32369bae47ed3dce00/src/Link.php#L37 with a type cast:

```php
public function __toString()
{
return (string) $this->href();
}
```
Regards

**Comment by hdodov** [comment]
Check out version 5.2.2. It should be fixed now.
