### ISSUE TITLE
support ?cc= in email type

### ISSUE THREAD

**Issue by illycz** [OblikStudio/kirby-link-field#76]
Now is impossible set cc for email link.

Thanks

**Comment by hdodov** [comment]
Could you explain your use case in more detail? I think it might be better to just not use the link field for that, because it seems you have a more advanced use case. You can maybe check out the [built-in Object field](https://getkirby.com/docs/reference/panel/fields/object).

**Comment by illycz** [comment]
I only need mailto to email and also set cc to another email: https://css-tricks.com/snippets/html/mailto-links/#aa-adding-cc-and-bcc

**Comment by hdodov** [comment]
I don't know. Seems like a pretty obscure feature to me. I'll leave the issue open. If a few other people upvote this - I'll add it in the plugin. Until then, I'd recommend using the Object field and putting whatever fields you want in there.

**Comment by illycz** [comment]
OK, I understand. For now, I'm using your hash field for this use case. Thanks for you time.
