### ISSUE TITLE
[k4] Plugin breaks link picker in Writer / Text fields

### ISSUE THREAD

**Issue by skraby** [OblikStudio/kirby-link-field#84]
In Kirby v4, there is [new dialogue](https://getkirby.com/releases/4.0#writer-field-improvements) for picking pages/files from within writer or text fields by clicking the link icon. This plugin brakes this functionality, the picker doesn't show up at all.

![image](https://github.com/OblikStudio/kirby-link-field/assets/12029893/eef561c7-7e36-4863-862d-93c9e1951095)

Temporary fix is to register this link field under different name (don't extend Kirby's link field).

**Comment by hdodov** [comment]
@skraby what do you mean by "register this link field under different name"? Different name in the blueprint, or?

**Comment by skraby** [comment]
@hdodov Sorry for the confusion. You register your plugin as `link`, effectively overriding Kirby's native link field. If you register it under different name, e.g. 'customLink', it works alongside Kirby's native link field. You need then change all occurrences of `type: link` to `type: customLink` in your blueprints of course.

**Comment by owzim** [comment]
@hdodov @skraby that's why we currenlty use a modified version of the this plugin in our k4 projects with the name of `linklegacy` 😜

**Comment by squareclouds** [comment]
@owzim can you please specify where you changed the name? only in the index.php?

**Comment by foxacid** [comment]
Many thanks for updating the plugin for k4. A fix for that namespace conflict fixed would be fantastic.

**Comment by foxacid** [comment]
> @owzim can you please specify where you changed the name? only in the index.php?

Line 6 of `app/index.js` and line 41 of `index.php`.

**Comment by hdodov** [comment]
@foxacid I'm really busy lately. If you're able to send a pull request, I'd be happy to merge it!

**Comment by foxacid** [comment]
@hdodov great, thanks. Pull request is out. Unfortunately the solution is a breaking change. However, it should only affect the field type name in blueprints. Similar to the suggestions above all occurences of `type: link` must be changed to `type: legacyLink`.

**Comment by squareclouds** [comment]
@foxacid cool that you did the pull request! one suggestion though, legacylink might not be the best wording. it kinda communicates that there is a new version somehow, and technically this plugin is rather an alternative to the official link field. maybe something like "linkfield" would be more transparent. for us, since we have using it before, legacy is understandable, but for people using it for the first time sounds strange. what do you think?

**Comment by foxacid** [comment]
@squareclouds I see what you mean. On the other hand I think that the current version of kirby-link-field really exists to provide legacy support for older projects. While there are functional differences between the two fields, for new projects I would definitely recommend to use the native K4 link field (e.g. as part of an object field). I think the plugin developer recommends the same and I'll leave the name choice to the original author.

**Comment by hdodov** [comment]
Yep, I definitely think users of the plugin should move to the native link field in Kirby. It's supported by the core team and will continue to do so during version updates. This really is a field of older projects where such a field didn't exist.

I've published version 6.0.1 of the plugin with the fix. Let me know if it works. I didn't have time to test.

**Comment by MathiasGmeiner** [comment]
The update is missing in the root index.js
It is still named "link" there
e.g. `components: { "k-link-field-preview": L },`

**Comment by hdodov** [comment]
@MathiasGmeiner yep, you're right. It was missing from the compiled JS. I've published version 6.0.2 which should fix this. Could you test it out?

**Comment by foxacid** [comment]
Sorry I forgot to check in the compiled code. I just tested 6.0.2 and it works fine.

**Comment by MathiasGmeiner** [comment]
@hdodov it works great now, thank you!
