### ISSUE TITLE
$link->attr() method should add `rel="noopener noreferrer"`

### ISSUE THREAD

**Issue by fabianmichael** [OblikStudio/kirby-link-field#9]
The `$link` object is a bit incosistent, when it comes to handling popups:

- `$link->tag()`: Adds the `rel="noopener noreferrer"` attrbute, when link is a popup
- `$link->attr()`: Does not add the `rel` attribute

It would be more consistent, if both methods would add the `rel` attribute.

**Comment by hdodov** [comment]
That's because `tag()` uses Kirby's internal functionality for creating links. `attr()` creates only attributes based on the input data - `_target` if it's a popup, `href` based on the URL type, etc.

It makes sense to add this attribute by default, though.

**Comment by hdodov** [comment]
✅
